review changes made
TheCSharpAcademy/CodeReviews.Console.Drinks pull request #92
Opened 2024-10-02 13:20 UTC by mohammad-premtech

2024-10-02 18:27 UTC, stevietv requested changes

2024-10-02 18:27 UTC, stevietv commented on DrinksInfo.Mo/DrinksInfoAPI/DrinksInfoAPI/UI/ConsoleUI.cs
> +        if (!string.IsNullOrEmpty(drinkDetails.StrIBA))
Hi @mohammad-premtech - these two lines need a fix before the program can run. Not sure how you were able to build and test it with this in!

2024-10-02 18:29 UTC, stevietv requested changes

2024-10-02 18:29 UTC, stevietv commented on DrinksInfo.Mo/DrinksInfoAPI/DrinksInfoAPI/UI/ConsoleUI.cs
> +            Console.WriteLine($"IBA: {drinkDetails.StrIBA}");
Hi @mohammad-premtech - these two lines need a fix before the program can run. Not sure how you were able to build and test it with this in!

2024-10-07 17:07 UTC, stevietv commented
hi @mohammad-premtech - just wanted to check in and see if you needed any help solving this?

2024-10-08 07:43 UTC, mohammad-premtech commented
Hi @stevietv : Will make the changes today.

2024-10-08 07:45 UTC, closed without merging